process.env.NODE_ENV = "test";
process.env.DATABASE_PROVIDER = "postgresql";
process.env.DATABASE_URL = "postgresql://postgres:test@localhost:5432/email_a11y_qa_test?schema=public";
process.env.FRONTEND_URL = "http://localhost:5173";
process.env.CORS_ALLOWED_ORIGINS = "http://localhost:5173";
process.env.JWT_SECRET = "test-only-secret-with-more-than-32-bytes-long";
process.env.JWT_ISSUER = "auth-template-test-api";
process.env.JWT_AUDIENCE = "auth-template-test-web";
process.env.JWT_TTL_SECONDS = "900";
process.env.REMEMBER_TTL_SECONDS = "2592000";
process.env.MAX_REMEMBERED_SESSIONS = "5";
process.env.BCRYPT_ROUNDS = "4";
process.env.PASSWORD_MAX_AGE_DAYS = "90";
process.env.PASSWORD_RESET_TTL_SECONDS = "1800";
process.env.EMAIL_VERIFICATION_TTL_SECONDS = "86400";
process.env.APP_NAME = "Auth Template Test";
process.env.SMTP_HOST = "";
process.env.MAIL_FROM = "";
